CREATE TYPE "public"."submission_event" AS ENUM('bingo', 'leagues');--> statement-breakpoint
CREATE TYPE "public"."submission_status" AS ENUM('pending', 'submitted', 'approved', 'approved_missing_member', 'denied', 'deleted_by_user');--> statement-breakpoint
CREATE TABLE "items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	CONSTRAINT "items_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "members" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "members_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"display_name" text NOT NULL,
	"main_rsn" text,
	"alt_rsn" text,
	"rank_id" smallint NOT NULL,
	"clan_points" integer DEFAULT 0 NOT NULL,
	"claimed_diary_tier_id" smallint,
	"is_active" boolean DEFAULT false NOT NULL,
	"joined_at" timestamp with time zone,
	"left_at" timestamp with time zone,
	"birthday" date,
	"nationality" char(2) DEFAULT 'AQ' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "members_discord_accounts" (
	"member_id" bigint PRIMARY KEY NOT NULL,
	"discord_id" bigint NOT NULL,
	"avatar_url" text,
	CONSTRAINT "members_discord_accounts_discord_id_unique" UNIQUE("discord_id")
);
--> statement-breakpoint
CREATE TABLE "personal_best_participants" (
	"personal_best_id" integer NOT NULL,
	"member_id" bigint NOT NULL,
	CONSTRAINT "personal_best_participants_personal_best_id_member_id_pk" PRIMARY KEY("personal_best_id","member_id")
);
--> statement-breakpoint
CREATE TABLE "personal_bests" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "personal_bests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"member_id" bigint NOT NULL,
	"content_id" integer NOT NULL,
	"scale" smallint NOT NULL,
	"time" interval NOT NULL,
	"image_url" text,
	"status" "submission_status" NOT NULL,
	"submitted_at" timestamp with time zone,
	"reviewed_by" bigint,
	"reviewed_at" timestamp with time zone,
	"review_note" text
);
--> statement-breakpoint
CREATE TABLE "points" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "points_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"member_id" bigint NOT NULL,
	"submission_id" integer,
	"value" integer NOT NULL,
	"notes" text,
	"awarded_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "points_timeline_events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "points_timeline_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"occurred_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ranks" (
	"id" smallint PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"in_game_name" text,
	"discord_role_id" bigint,
	"clan_point_requirement" integer DEFAULT 0 NOT NULL,
	"diary_point_requirement" integer DEFAULT 0 NOT NULL,
	"master_diary_requirement" integer DEFAULT 0 NOT NULL,
	"maintenance_point_requirement" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "ranks_in_game_name_unique" UNIQUE("in_game_name"),
	CONSTRAINT "ranks_discord_role_id_unique" UNIQUE("discord_role_id")
);
--> statement-breakpoint
CREATE TABLE "speedrun_content" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "speedrun_content_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"image_url" text,
	CONSTRAINT "speedrun_content_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "speedrun_diary_rewards" (
	"tier_id" smallint PRIMARY KEY NOT NULL,
	"required_diary_points" smallint NOT NULL,
	"clan_points" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "speedrun_diary_tiers" (
	"id" smallint PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"points" smallint NOT NULL,
	CONSTRAINT "speedrun_diary_tiers_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "speedrun_diary_times" (
	"content_id" integer NOT NULL,
	"scale" smallint NOT NULL,
	"tier_id" smallint NOT NULL,
	"time" interval NOT NULL,
	CONSTRAINT "speedrun_diary_times_content_id_scale_tier_id_pk" PRIMARY KEY("content_id","scale","tier_id")
);
--> statement-breakpoint
CREATE TABLE "submission_participants" (
	"submission_id" integer NOT NULL,
	"member_id" bigint NOT NULL,
	CONSTRAINT "submission_participants_submission_id_member_id_pk" PRIMARY KEY("submission_id","member_id")
);
--> statement-breakpoint
CREATE TABLE "submissions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "submissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"member_id" bigint NOT NULL,
	"item_id" integer,
	"item_name" text,
	"value_millions" integer,
	"image_url" text,
	"discord_message_url" text,
	"event" "submission_event",
	"status" "submission_status" NOT NULL,
	"submitted_at" timestamp with time zone NOT NULL,
	"reviewed_by" bigint,
	"reviewed_at" timestamp with time zone,
	"review_note" text
);
--> statement-breakpoint
ALTER TABLE "members" ADD CONSTRAINT "members_rank_id_ranks_id_fk" FOREIGN KEY ("rank_id") REFERENCES "public"."ranks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "members" ADD CONSTRAINT "members_claimed_diary_tier_id_speedrun_diary_tiers_id_fk" FOREIGN KEY ("claimed_diary_tier_id") REFERENCES "public"."speedrun_diary_tiers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "members_discord_accounts" ADD CONSTRAINT "members_discord_accounts_member_id_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."members"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "personal_best_participants" ADD CONSTRAINT "personal_best_participants_personal_best_id_personal_bests_id_fk" FOREIGN KEY ("personal_best_id") REFERENCES "public"."personal_bests"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "personal_best_participants" ADD CONSTRAINT "personal_best_participants_member_id_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."members"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "personal_bests" ADD CONSTRAINT "personal_bests_member_id_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."members"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "personal_bests" ADD CONSTRAINT "personal_bests_content_id_speedrun_content_id_fk" FOREIGN KEY ("content_id") REFERENCES "public"."speedrun_content"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "personal_bests" ADD CONSTRAINT "personal_bests_reviewed_by_members_id_fk" FOREIGN KEY ("reviewed_by") REFERENCES "public"."members"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "points" ADD CONSTRAINT "points_member_id_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."members"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "points" ADD CONSTRAINT "points_submission_id_submissions_id_fk" FOREIGN KEY ("submission_id") REFERENCES "public"."submissions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "speedrun_diary_rewards" ADD CONSTRAINT "speedrun_diary_rewards_tier_id_speedrun_diary_tiers_id_fk" FOREIGN KEY ("tier_id") REFERENCES "public"."speedrun_diary_tiers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "speedrun_diary_times" ADD CONSTRAINT "speedrun_diary_times_content_id_speedrun_content_id_fk" FOREIGN KEY ("content_id") REFERENCES "public"."speedrun_content"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "speedrun_diary_times" ADD CONSTRAINT "speedrun_diary_times_tier_id_speedrun_diary_tiers_id_fk" FOREIGN KEY ("tier_id") REFERENCES "public"."speedrun_diary_tiers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "submission_participants" ADD CONSTRAINT "submission_participants_submission_id_submissions_id_fk" FOREIGN KEY ("submission_id") REFERENCES "public"."submissions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "submission_participants" ADD CONSTRAINT "submission_participants_member_id_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."members"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "submissions" ADD CONSTRAINT "submissions_member_id_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."members"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "submissions" ADD CONSTRAINT "submissions_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "submissions" ADD CONSTRAINT "submissions_reviewed_by_members_id_fk" FOREIGN KEY ("reviewed_by") REFERENCES "public"."members"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "members_rank_id_index" ON "members" USING btree ("rank_id");--> statement-breakpoint
CREATE INDEX "members_clan_points_index" ON "members" USING btree ("clan_points" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "members_display_name_index" ON "members" USING btree ("display_name");--> statement-breakpoint
CREATE INDEX "personal_best_participants_member_id_index" ON "personal_best_participants" USING btree ("member_id");--> statement-breakpoint
CREATE INDEX "personal_bests_member_id_index" ON "personal_bests" USING btree ("member_id");--> statement-breakpoint
CREATE INDEX "personal_bests_content_id_scale_time_index" ON "personal_bests" USING btree ("content_id","scale","time");--> statement-breakpoint
CREATE INDEX "points_member_id_awarded_at_index" ON "points" USING btree ("member_id","awarded_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "points_submission_id_index" ON "points" USING btree ("submission_id");--> statement-breakpoint
CREATE INDEX "submission_participants_member_id_index" ON "submission_participants" USING btree ("member_id");--> statement-breakpoint
CREATE INDEX "submissions_member_id_index" ON "submissions" USING btree ("member_id");--> statement-breakpoint
CREATE INDEX "submissions_item_id_index" ON "submissions" USING btree ("item_id");--> statement-breakpoint
CREATE INDEX "submissions_status_index" ON "submissions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "submissions_submitted_at_index" ON "submissions" USING btree ("submitted_at" DESC NULLS LAST);