CREATE EXTENSION IF NOT EXISTS citext;--> statement-breakpoint
CREATE EXTENSION IF NOT EXISTS pg_trgm;--> statement-breakpoint
CREATE TABLE "boss_uniques" (
	"boss_id" integer NOT NULL,
	"item_id" integer NOT NULL,
	"drop_rate" integer NOT NULL,
	CONSTRAINT "boss_uniques_boss_id_item_id_pk" PRIMARY KEY("boss_id","item_id")
);
--> statement-breakpoint
CREATE TABLE "bosses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bosses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" citext NOT NULL,
	"kills_per_hour" numeric(6, 2),
	"wom_metric" text,
	"wom_kills_per_hour" numeric(6, 2),
	CONSTRAINT "bosses_wom_metric_unique" UNIQUE("wom_metric"),
	CONSTRAINT "bosses_name_unique" UNIQUE("name")
);
--> statement-breakpoint
ALTER TABLE "items" ALTER COLUMN "name" SET DATA TYPE citext;--> statement-breakpoint
ALTER TABLE "personal_bests" ALTER COLUMN "content_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "items" ADD COLUMN "osrs_item_id" integer;--> statement-breakpoint
ALTER TABLE "speedrun_content" ADD COLUMN "boss_id" integer;--> statement-breakpoint
ALTER TABLE "boss_uniques" ADD CONSTRAINT "boss_uniques_boss_id_bosses_id_fk" FOREIGN KEY ("boss_id") REFERENCES "public"."bosses"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "boss_uniques" ADD CONSTRAINT "boss_uniques_item_id_items_id_fk" FOREIGN KEY ("item_id") REFERENCES "public"."items"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "boss_uniques_item_id_index" ON "boss_uniques" USING btree ("item_id");--> statement-breakpoint
ALTER TABLE "speedrun_content" ADD CONSTRAINT "speedrun_content_boss_id_bosses_id_fk" FOREIGN KEY ("boss_id") REFERENCES "public"."bosses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "items" ADD CONSTRAINT "items_osrs_item_id_unique" UNIQUE("osrs_item_id");
--> statement-breakpoint
CREATE INDEX "items_name_search_index" ON "items" USING gin ("name" gin_trgm_ops);
