CREATE TYPE "public"."audit_action" AS ENUM('catalogue_changed', 'diary_tier_claimed', 'member_joined', 'member_left', 'other', 'personal_best_reviewed', 'points_awarded', 'rank_changed', 'role_changed', 'rsn_changed', 'submission_reviewed');--> statement-breakpoint
CREATE TYPE "public"."audit_source" AS ENUM('bot', 'server', 'web_app', 'worker');--> statement-breakpoint
CREATE TABLE "audit_log" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"acting_member_id" bigint,
	"action" "audit_action" NOT NULL,
	"note" text,
	"occurred_at" timestamp with time zone NOT NULL,
	"source" "audit_source" NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit_log_members" (
	"audit_log_id" bigint NOT NULL,
	"member_id" bigint NOT NULL,
	CONSTRAINT "audit_log_members_audit_log_id_member_id_pk" PRIMARY KEY("audit_log_id","member_id")
);
--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_acting_member_id_members_id_fk" FOREIGN KEY ("acting_member_id") REFERENCES "public"."members"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_log_members" ADD CONSTRAINT "audit_log_members_audit_log_id_audit_log_id_fk" FOREIGN KEY ("audit_log_id") REFERENCES "public"."audit_log"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_log_members" ADD CONSTRAINT "audit_log_members_member_id_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."members"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "audit_log_occurred_at_index" ON "audit_log" USING btree ("occurred_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "audit_log_action_index" ON "audit_log" USING btree ("action");--> statement-breakpoint
CREATE INDEX "audit_log_members_member_id_index" ON "audit_log_members" USING btree ("member_id");