/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as siteLayoutRouteImport } from './routes/(site)/_layout'
import { Route as siteLoginRouteImport } from './routes/(site)/login'
import { Route as siteMembersIndexRouteImport } from './routes/(site)/members/index'
import { Route as siteMembersMemberIdLayoutRouteImport } from './routes/(site)/members/$memberId/_layout'
import { Route as siteWikiIndexRouteImport } from './routes/(site)/wiki/index'
import { Route as siteWikiArticleLayoutRouteImport } from './routes/(site)/wiki/$article/_layout'
import { Route as siteMembersMemberIdIndexRouteImport } from './routes/(site)/members/$memberId/index'
import { Route as siteWikiArticleIndexRouteImport } from './routes/(site)/wiki/$article/index'
import { Route as siteWikiArticleDiscussionRouteImport } from './routes/(site)/wiki/$article/discussion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const siteLayoutRoute = siteLayoutRouteImport.update({
  id: '/(site)',
  getParentRoute: () => rootRouteImport,
} as any)
const siteLoginRoute = siteLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => siteLayoutRoute,
} as any)
const siteMembersIndexRoute = siteMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => siteLayoutRoute,
} as any)
const siteMembersMemberIdLayoutRoute =
  siteMembersMemberIdLayoutRouteImport.update({
    id: '/members/$memberId',
    path: '/members/$memberId',
    getParentRoute: () => siteLayoutRoute,
  } as any)
const siteWikiIndexRoute = siteWikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => siteLayoutRoute,
} as any)
const siteWikiArticleLayoutRoute = siteWikiArticleLayoutRouteImport.update({
  id: '/wiki/$article',
  path: '/wiki/$article',
  getParentRoute: () => siteLayoutRoute,
} as any)
const siteMembersMemberIdIndexRoute =
  siteMembersMemberIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => siteMembersMemberIdLayoutRoute,
  } as any)
const siteWikiArticleIndexRoute = siteWikiArticleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => siteWikiArticleLayoutRoute,
} as any)
const siteWikiArticleDiscussionRoute =
  siteWikiArticleDiscussionRouteImport.update({
    id: '/discussion',
    path: '/discussion',
    getParentRoute: () => siteWikiArticleLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof siteLoginRoute
  '/members/$memberId': typeof siteMembersMemberIdLayoutRouteWithChildren
  '/wiki/$article': typeof siteWikiArticleLayoutRouteWithChildren
  '/members/': typeof siteMembersIndexRoute
  '/wiki/': typeof siteWikiIndexRoute
  '/wiki/$article/discussion': typeof siteWikiArticleDiscussionRoute
  '/members/$memberId/': typeof siteMembersMemberIdIndexRoute
  '/wiki/$article/': typeof siteWikiArticleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof siteLoginRoute
  '/members': typeof siteMembersIndexRoute
  '/wiki': typeof siteWikiIndexRoute
  '/wiki/$article/discussion': typeof siteWikiArticleDiscussionRoute
  '/members/$memberId': typeof siteMembersMemberIdIndexRoute
  '/wiki/$article': typeof siteWikiArticleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(site)': typeof siteLayoutRouteWithChildren
  '/(site)/login': typeof siteLoginRoute
  '/(site)/members/$memberId': typeof siteMembersMemberIdLayoutRouteWithChildren
  '/(site)/wiki/$article': typeof siteWikiArticleLayoutRouteWithChildren
  '/(site)/members/': typeof siteMembersIndexRoute
  '/(site)/wiki/': typeof siteWikiIndexRoute
  '/(site)/wiki/$article/discussion': typeof siteWikiArticleDiscussionRoute
  '/(site)/members/$memberId/': typeof siteMembersMemberIdIndexRoute
  '/(site)/wiki/$article/': typeof siteWikiArticleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/members/$memberId'
    | '/wiki/$article'
    | '/members/'
    | '/wiki/'
    | '/wiki/$article/discussion'
    | '/members/$memberId/'
    | '/wiki/$article/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/members'
    | '/wiki'
    | '/wiki/$article/discussion'
    | '/members/$memberId'
    | '/wiki/$article'
  id:
    | '__root__'
    | '/'
    | '/(site)'
    | '/(site)/login'
    | '/(site)/members/$memberId'
    | '/(site)/wiki/$article'
    | '/(site)/members/'
    | '/(site)/wiki/'
    | '/(site)/wiki/$article/discussion'
    | '/(site)/members/$memberId/'
    | '/(site)/wiki/$article/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  siteLayoutRoute: typeof siteLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(site)': {
      id: '/(site)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof siteLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(site)/login': {
      id: '/(site)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof siteLoginRouteImport
      parentRoute: typeof siteLayoutRoute
    }
    '/(site)/members/': {
      id: '/(site)/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof siteMembersIndexRouteImport
      parentRoute: typeof siteLayoutRoute
    }
    '/(site)/members/$memberId': {
      id: '/(site)/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof siteMembersMemberIdLayoutRouteImport
      parentRoute: typeof siteLayoutRoute
    }
    '/(site)/wiki/': {
      id: '/(site)/wiki/'
      path: '/wiki'
      fullPath: '/wiki/'
      preLoaderRoute: typeof siteWikiIndexRouteImport
      parentRoute: typeof siteLayoutRoute
    }
    '/(site)/wiki/$article': {
      id: '/(site)/wiki/$article'
      path: '/wiki/$article'
      fullPath: '/wiki/$article'
      preLoaderRoute: typeof siteWikiArticleLayoutRouteImport
      parentRoute: typeof siteLayoutRoute
    }
    '/(site)/members/$memberId/': {
      id: '/(site)/members/$memberId/'
      path: '/'
      fullPath: '/members/$memberId/'
      preLoaderRoute: typeof siteMembersMemberIdIndexRouteImport
      parentRoute: typeof siteMembersMemberIdLayoutRoute
    }
    '/(site)/wiki/$article/': {
      id: '/(site)/wiki/$article/'
      path: '/'
      fullPath: '/wiki/$article/'
      preLoaderRoute: typeof siteWikiArticleIndexRouteImport
      parentRoute: typeof siteWikiArticleLayoutRoute
    }
    '/(site)/wiki/$article/discussion': {
      id: '/(site)/wiki/$article/discussion'
      path: '/discussion'
      fullPath: '/wiki/$article/discussion'
      preLoaderRoute: typeof siteWikiArticleDiscussionRouteImport
      parentRoute: typeof siteWikiArticleLayoutRoute
    }
  }
}

interface siteMembersMemberIdLayoutRouteChildren {
  siteMembersMemberIdIndexRoute: typeof siteMembersMemberIdIndexRoute
}

const siteMembersMemberIdLayoutRouteChildren: siteMembersMemberIdLayoutRouteChildren =
  {
    siteMembersMemberIdIndexRoute: siteMembersMemberIdIndexRoute,
  }

const siteMembersMemberIdLayoutRouteWithChildren =
  siteMembersMemberIdLayoutRoute._addFileChildren(
    siteMembersMemberIdLayoutRouteChildren,
  )

interface siteWikiArticleLayoutRouteChildren {
  siteWikiArticleDiscussionRoute: typeof siteWikiArticleDiscussionRoute
  siteWikiArticleIndexRoute: typeof siteWikiArticleIndexRoute
}

const siteWikiArticleLayoutRouteChildren: siteWikiArticleLayoutRouteChildren = {
  siteWikiArticleDiscussionRoute: siteWikiArticleDiscussionRoute,
  siteWikiArticleIndexRoute: siteWikiArticleIndexRoute,
}

const siteWikiArticleLayoutRouteWithChildren =
  siteWikiArticleLayoutRoute._addFileChildren(
    siteWikiArticleLayoutRouteChildren,
  )

interface siteLayoutRouteChildren {
  siteLoginRoute: typeof siteLoginRoute
  siteMembersMemberIdLayoutRoute: typeof siteMembersMemberIdLayoutRouteWithChildren
  siteWikiArticleLayoutRoute: typeof siteWikiArticleLayoutRouteWithChildren
  siteMembersIndexRoute: typeof siteMembersIndexRoute
  siteWikiIndexRoute: typeof siteWikiIndexRoute
}

const siteLayoutRouteChildren: siteLayoutRouteChildren = {
  siteLoginRoute: siteLoginRoute,
  siteMembersMemberIdLayoutRoute: siteMembersMemberIdLayoutRouteWithChildren,
  siteWikiArticleLayoutRoute: siteWikiArticleLayoutRouteWithChildren,
  siteMembersIndexRoute: siteMembersIndexRoute,
  siteWikiIndexRoute: siteWikiIndexRoute,
}

const siteLayoutRouteWithChildren = siteLayoutRoute._addFileChildren(
  siteLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  siteLayoutRoute: siteLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
