/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appLayoutRouteImport } from './routes/(app)/_layout'
import { Route as appauthenticatedLayoutRouteImport } from './routes/(app)/(authenticated)/_layout'
import { Route as apppublicIndexRouteImport } from './routes/(app)/(public)/index'
import { Route as apppublicAboutRouteImport } from './routes/(app)/(public)/about'
import { Route as appauthenticatedAuthenticatedRouteImport } from './routes/(app)/(authenticated)/authenticated'

const appLayoutRoute = appLayoutRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appauthenticatedLayoutRoute = appauthenticatedLayoutRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => appLayoutRoute,
} as any)
const apppublicIndexRoute = apppublicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => appLayoutRoute,
} as any)
const apppublicAboutRoute = apppublicAboutRouteImport.update({
  id: '/(public)/about',
  path: '/about',
  getParentRoute: () => appLayoutRoute,
} as any)
const appauthenticatedAuthenticatedRoute =
  appauthenticatedAuthenticatedRouteImport.update({
    id: '/authenticated',
    path: '/authenticated',
    getParentRoute: () => appauthenticatedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/authenticated': typeof appauthenticatedAuthenticatedRoute
  '/about': typeof apppublicAboutRoute
  '/': typeof apppublicIndexRoute
}
export interface FileRoutesByTo {
  '/authenticated': typeof appauthenticatedAuthenticatedRoute
  '/about': typeof apppublicAboutRoute
  '/': typeof apppublicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appLayoutRouteWithChildren
  '/(app)/(authenticated)': typeof appauthenticatedLayoutRouteWithChildren
  '/(app)/(authenticated)/authenticated': typeof appauthenticatedAuthenticatedRoute
  '/(app)/(public)/about': typeof apppublicAboutRoute
  '/(app)/(public)/': typeof apppublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/authenticated' | '/about' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/authenticated' | '/about' | '/'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/(authenticated)'
    | '/(app)/(authenticated)/authenticated'
    | '/(app)/(public)/about'
    | '/(app)/(public)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appLayoutRoute: typeof appLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(authenticated)': {
      id: '/(app)/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appauthenticatedLayoutRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/(public)/': {
      id: '/(app)/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof apppublicIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/(public)/about': {
      id: '/(app)/(public)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof apppublicAboutRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/(authenticated)/authenticated': {
      id: '/(app)/(authenticated)/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof appauthenticatedAuthenticatedRouteImport
      parentRoute: typeof appauthenticatedLayoutRoute
    }
  }
}

interface appauthenticatedLayoutRouteChildren {
  appauthenticatedAuthenticatedRoute: typeof appauthenticatedAuthenticatedRoute
}

const appauthenticatedLayoutRouteChildren: appauthenticatedLayoutRouteChildren =
  {
    appauthenticatedAuthenticatedRoute: appauthenticatedAuthenticatedRoute,
  }

const appauthenticatedLayoutRouteWithChildren =
  appauthenticatedLayoutRoute._addFileChildren(
    appauthenticatedLayoutRouteChildren,
  )

interface appLayoutRouteChildren {
  appauthenticatedLayoutRoute: typeof appauthenticatedLayoutRouteWithChildren
  apppublicAboutRoute: typeof apppublicAboutRoute
  apppublicIndexRoute: typeof apppublicIndexRoute
}

const appLayoutRouteChildren: appLayoutRouteChildren = {
  appauthenticatedLayoutRoute: appauthenticatedLayoutRouteWithChildren,
  apppublicAboutRoute: apppublicAboutRoute,
  apppublicIndexRoute: apppublicIndexRoute,
}

const appLayoutRouteWithChildren = appLayoutRoute._addFileChildren(
  appLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appLayoutRoute: appLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
