// Wise Old Man metric keys mapped to their in-game names. Declaration order is display order:
// skills follow the in-game skill tab, activities the hiscores, bosses A-Z.

export enum Skill {
  overall = "Overall",
  attack = "Attack",
  defence = "Defence",
  strength = "Strength",
  hitpoints = "Hitpoints",
  ranged = "Ranged",
  prayer = "Prayer",
  magic = "Magic",
  cooking = "Cooking",
  woodcutting = "Woodcutting",
  fletching = "Fletching",
  fishing = "Fishing",
  firemaking = "Firemaking",
  crafting = "Crafting",
  smithing = "Smithing",
  mining = "Mining",
  herblore = "Herblore",
  agility = "Agility",
  thieving = "Thieving",
  slayer = "Slayer",
  farming = "Farming",
  runecrafting = "Runecrafting",
  hunter = "Hunter",
  construction = "Construction",
  sailing = "Sailing"
}

export enum Activity {
  bounty_hunter_hunter = "Bounty Hunter (Hunter)",
  bounty_hunter_rogue = "Bounty Hunter (Rogue)",
  clue_scrolls_all = "Clue Scrolls (All)",
  clue_scrolls_beginner = "Clue Scrolls (Beginner)",
  clue_scrolls_easy = "Clue Scrolls (Easy)",
  clue_scrolls_medium = "Clue Scrolls (Medium)",
  clue_scrolls_hard = "Clue Scrolls (Hard)",
  clue_scrolls_elite = "Clue Scrolls (Elite)",
  clue_scrolls_master = "Clue Scrolls (Master)",
  last_man_standing = "Last Man Standing",
  pvp_arena = "PvP Arena",
  soul_wars_zeal = "Soul Wars Zeal",
  guardians_of_the_rift = "Guardians of the Rift",
  colosseum_glory = "Colosseum Glory",
  collections_logged = "Collections Logged"
}

export enum Boss {
  abyssal_sire = "Abyssal Sire",
  alchemical_hydra = "Alchemical Hydra",
  amoxliatl = "Amoxliatl",
  araxxor = "Araxxor",
  artio = "Artio",
  barrows_chests = "Barrows Chests",
  brutus = "Brutus",
  bryophyta = "Bryophyta",
  callisto = "Callisto",
  calvarion = "Calvar'ion",
  cerberus = "Cerberus",
  chambers_of_xeric = "Chambers of Xeric",
  chambers_of_xeric_challenge_mode = "Chambers of Xeric (Challenge Mode)",
  chaos_elemental = "Chaos Elemental",
  chaos_fanatic = "Chaos Fanatic",
  commander_zilyana = "Commander Zilyana",
  corporeal_beast = "Corporeal Beast",
  crazy_archaeologist = "Crazy Archaeologist",
  dagannoth_prime = "Dagannoth Prime",
  dagannoth_rex = "Dagannoth Rex",
  dagannoth_supreme = "Dagannoth Supreme",
  deranged_archaeologist = "Deranged Archaeologist",
  doom_of_mokhaiotl = "Doom of Mokhaiotl",
  duke_sucellus = "Duke Sucellus",
  general_graardor = "General Graardor",
  giant_mole = "Giant Mole",
  grotesque_guardians = "Grotesque Guardians",
  hespori = "Hespori",
  kalphite_queen = "Kalphite Queen",
  king_black_dragon = "King Black Dragon",
  kraken = "Kraken",
  kreearra = "Kree'arra",
  kril_tsutsaroth = "K'ril Tsutsaroth",
  lunar_chests = "Lunar Chests",
  mad_angel = "Mad Angel",
  maggot_king = "Maggot King",
  mimic = "Mimic",
  nex = "Nex",
  nightmare = "Nightmare",
  obor = "Obor",
  phantom_muspah = "Phantom Muspah",
  phosanis_nightmare = "Phosani's Nightmare",
  sarachnis = "Sarachnis",
  scorpia = "Scorpia",
  scurrius = "Scurrius",
  shellbane_gryphon = "Shellbane Gryphon",
  skotizo = "Skotizo",
  sol_heredit = "Sol Heredit",
  spindel = "Spindel",
  tempoross = "Tempoross",
  the_corrupted_gauntlet = "The Corrupted Gauntlet",
  the_gauntlet = "The Gauntlet",
  the_hueycoatl = "The Hueycoatl",
  the_leviathan = "The Leviathan",
  the_royal_titans = "The Royal Titans",
  the_whisperer = "The Whisperer",
  theatre_of_blood = "Theatre of Blood",
  theatre_of_blood_hard_mode = "Theatre of Blood (Hard Mode)",
  thermonuclear_smoke_devil = "Thermonuclear Smoke Devil",
  tombs_of_amascut = "Tombs of Amascut",
  tombs_of_amascut_expert = "Tombs of Amascut (Expert)",
  tzkal_zuk = "TzKal-Zuk",
  tztok_jad = "TzTok-Jad",
  vardorvis = "Vardorvis",
  venenatis = "Venenatis",
  vetion = "Vet'ion",
  vorkath = "Vorkath",
  wintertodt = "Wintertodt",
  yama = "Yama",
  zalcano = "Zalcano",
  zulrah = "Zulrah"
}

// Wise Old Man derives these from the hiscores rather than reading them, but they sit alongside
// the rest as metrics.
export enum Computed {
  ehp = "EHP",
  ehb = "EHB"
}

export const METRICS = { ...Skill, ...Boss, ...Activity, ...Computed } as const;
export type Metric = keyof typeof METRICS;
