/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                    active?: "true" | "false";
                    search?: string;
                    sort?: components["schemas"]["MemberSortInput"];
                    order?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Member"][];
                            page: components["schemas"]["Page"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemberProfile"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members/{id}/diary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemberDiary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members/{id}/personal-bests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                    top?: number;
                    contentId?: number;
                    diary?: "true" | "false";
                    scale?: number;
                    sort?: components["schemas"]["PersonalBestSortInput"];
                    order?: "asc" | "desc";
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["RankedPersonalBest"][];
                            page: components["schemas"]["Page"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/personal-bests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                    contentId?: number;
                    diary?: "true" | "false";
                    scale?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PersonalBest"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/personal-bests/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    top?: number;
                    contentId?: number;
                    diary?: "true" | "false";
                    scale?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RankedPersonalBest"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ranks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Rank"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                    memberId?: string;
                    event?: "bingo" | "leagues";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Submission"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wom/players/{username}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    username: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PageInput: {
            limit: number;
            offset: number;
            total: number;
            hasNext: boolean;
            hasPrevious: boolean;
        };
        MemberRefInput: {
            id: string;
            displayName: string;
        };
        PersonalBestInput: {
            id: number;
            content: {
                id: number;
                name: string;
                imageUrl: string | null;
            };
            scale: number;
            timeSeconds: number;
            imageUrl: string | null;
            /** Format: date-time */
            submittedAt: string | null;
            submittedBy: components["schemas"]["MemberRefInput"];
            team: components["schemas"]["MemberRefInput"][];
        };
        RankedPersonalBestInput: {
            id: number;
            position: number;
            content: {
                id: number;
                name: string;
                imageUrl: string | null;
            };
            scale: number;
            timeSeconds: number;
            imageUrl: string | null;
            /** Format: date-time */
            submittedAt: string | null;
            submittedBy: components["schemas"]["MemberRefInput"];
            team: components["schemas"]["MemberRefInput"][];
        };
        MemberDiaryInput: {
            content: {
                id: number;
                name: string;
                imageUrl: string | null;
            };
            scale: number;
            pb: {
                id: number;
                timeSeconds: number;
                imageUrl: string | null;
            } | null;
            tier: {
                id: number;
                name: string;
                points: number;
            } | null;
            nextTier: {
                id: number;
                name: string;
                points: number;
                timeSeconds: number;
            } | null;
        };
        /** @enum {string} */
        PersonalBestSortInput: "content" | "scale" | "submittedAt" | "time";
        /** @enum {string} */
        MemberSortInput: "clanPoints" | "diaryPoints" | "displayName" | "joinedAt" | "masterDiaries" | "rank" | "totalEhb" | "totalEhp" | "totalExp" | "totalLevel";
        RankSummaryInput: {
            id: number;
            name: string;
            iconUrl: string | null;
        };
        ComputedInput: {
            metric: string;
            value: number;
            rank: number | null;
        };
        SkillInput: {
            skill: string;
            experience: number;
            level: number;
            rank: number | null;
            ehp: number;
        };
        BossInput: {
            boss: string;
            kills: number;
            rank: number | null;
            ehb: number;
        };
        ActivityInput: {
            activity: string;
            score: number;
            rank: number | null;
        };
        SnapshotInput: {
            /** Format: date-time */
            createdAt: string;
            computed: components["schemas"]["ComputedInput"][];
            skills: components["schemas"]["SkillInput"][];
            bosses: components["schemas"]["BossInput"][];
            activities: components["schemas"]["ActivityInput"][];
        };
        MemberInput: {
            id: string;
            displayName: string;
            nationality: string;
            discord: {
                id: string;
                avatarUrl: string | null;
            };
            rsn: {
                main: string | null;
                alt: string | null;
            };
            membership: {
                active: boolean;
                /** Format: date-time */
                joinedAt: string | null;
                /** Format: date-time */
                leftAt: string | null;
                rank: components["schemas"]["RankSummaryInput"];
                points: number;
            };
            diary: {
                points: number;
                masterDiaries: number;
                claimedTier: {
                    id: number;
                    name: string;
                } | null;
            };
            wom: {
                playerId: number;
                username: string;
                displayName: string;
                type: string;
                build: string;
                status: string | null;
                totalLevel: number | null;
                totalExp: number;
                totalEhp: number;
                totalEhb: number;
                timeToMax: number | null;
                timeTo200m: number | null;
                /** Format: date-time */
                updatedAt: string | null;
                /** Format: date-time */
                lastChangedAt: string | null;
            } | null;
        };
        MemberProfileInput: {
            id: string;
            displayName: string;
            nationality: string;
            discord: {
                id: string;
                avatarUrl: string | null;
            };
            rsn: {
                main: string | null;
                alt: string | null;
            };
            membership: {
                active: boolean;
                /** Format: date-time */
                joinedAt: string | null;
                /** Format: date-time */
                leftAt: string | null;
                rank: components["schemas"]["RankSummaryInput"];
                points: number;
            };
            diary: {
                points: number;
                masterDiaries: number;
                claimedTier: {
                    id: number;
                    name: string;
                } | null;
            };
            progression: {
                eligibleRank: components["schemas"]["RankSummaryInput"] | null;
                nextRank: {
                    points: {
                        id: number;
                        name: string;
                        iconUrl: string | null;
                        requirements: {
                            clanPoints: number;
                            diaryPoints: number;
                            masterDiaries: number;
                        };
                    } | null;
                    diary: {
                        id: number;
                        name: string;
                        iconUrl: string | null;
                        requirements: {
                            clanPoints: number;
                            diaryPoints: number;
                            masterDiaries: number;
                        };
                    } | null;
                };
            };
            wom: {
                playerId: number;
                username: string;
                displayName: string;
                type: string;
                build: string;
                status: string | null;
                totalLevel: number | null;
                totalExp: number;
                totalEhp: number;
                totalEhb: number;
                timeToMax: number | null;
                timeTo200m: number | null;
                /** Format: date-time */
                updatedAt: string | null;
                /** Format: date-time */
                lastChangedAt: string | null;
                latestSnapshot?: components["schemas"]["SnapshotInput"];
            } | null;
        };
        RankInput: {
            id: number;
            name: string;
            iconUrl: string | null;
            discordRoleId: string | null;
            requirements: {
                clanPoints: number;
                diaryPoints: number;
                masterDiaries: number;
                maintenancePoints: number;
            };
        };
        SubmissionInput: {
            id: number;
            item: {
                id: number | null;
                name: string | null;
            };
            valueMillions: number | null;
            /** @enum {string|null} */
            event: "bingo" | "leagues" | null;
            imageUrl: string | null;
            discordMessageUrl: string | null;
            /** Format: date-time */
            submittedAt: string;
            submittedBy: components["schemas"]["MemberRefInput"];
            participants: {
                id: string;
                displayName: string;
                points: number | null;
            }[];
        };
        Page: {
            limit: number;
            offset: number;
            total: number;
            hasNext: boolean;
            hasPrevious: boolean;
        };
        MemberRef: {
            id: string;
            displayName: string;
        };
        PersonalBest: {
            id: number;
            content: {
                id: number;
                name: string;
                imageUrl: string | null;
            };
            scale: number;
            timeSeconds: number;
            imageUrl: string | null;
            /** Format: date-time */
            submittedAt: string | null;
            submittedBy: components["schemas"]["MemberRef"];
            team: components["schemas"]["MemberRef"][];
        };
        RankedPersonalBest: {
            id: number;
            position: number;
            content: {
                id: number;
                name: string;
                imageUrl: string | null;
            };
            scale: number;
            timeSeconds: number;
            imageUrl: string | null;
            /** Format: date-time */
            submittedAt: string | null;
            submittedBy: components["schemas"]["MemberRef"];
            team: components["schemas"]["MemberRef"][];
        };
        MemberDiary: {
            content: {
                id: number;
                name: string;
                imageUrl: string | null;
            };
            scale: number;
            pb: {
                id: number;
                timeSeconds: number;
                imageUrl: string | null;
            } | null;
            tier: {
                id: number;
                name: string;
                points: number;
            } | null;
            nextTier: {
                id: number;
                name: string;
                points: number;
                timeSeconds: number;
            } | null;
        };
        /** @enum {string} */
        PersonalBestSort: "content" | "scale" | "submittedAt" | "time";
        /** @enum {string} */
        MemberSort: "clanPoints" | "diaryPoints" | "displayName" | "joinedAt" | "masterDiaries" | "rank" | "totalEhb" | "totalEhp" | "totalExp" | "totalLevel";
        RankSummary: {
            id: number;
            name: string;
            iconUrl: string | null;
        };
        Computed: {
            metric: string;
            value: number;
            rank: number | null;
        };
        Skill: {
            skill: string;
            experience: number;
            level: number;
            rank: number | null;
            ehp: number;
        };
        Boss: {
            boss: string;
            kills: number;
            rank: number | null;
            ehb: number;
        };
        Activity: {
            activity: string;
            score: number;
            rank: number | null;
        };
        Snapshot: {
            /** Format: date-time */
            createdAt: string;
            computed: components["schemas"]["Computed"][];
            skills: components["schemas"]["Skill"][];
            bosses: components["schemas"]["Boss"][];
            activities: components["schemas"]["Activity"][];
        };
        Member: {
            id: string;
            displayName: string;
            nationality: string;
            discord: {
                id: string;
                avatarUrl: string | null;
            };
            rsn: {
                main: string | null;
                alt: string | null;
            };
            membership: {
                active: boolean;
                /** Format: date-time */
                joinedAt: string | null;
                /** Format: date-time */
                leftAt: string | null;
                rank: components["schemas"]["RankSummary"];
                points: number;
            };
            diary: {
                points: number;
                masterDiaries: number;
                claimedTier: {
                    id: number;
                    name: string;
                } | null;
            };
            wom: {
                playerId: number;
                username: string;
                displayName: string;
                type: string;
                build: string;
                status: string | null;
                totalLevel: number | null;
                totalExp: number;
                totalEhp: number;
                totalEhb: number;
                timeToMax: number | null;
                timeTo200m: number | null;
                /** Format: date-time */
                updatedAt: string | null;
                /** Format: date-time */
                lastChangedAt: string | null;
            } | null;
        };
        MemberProfile: {
            id: string;
            displayName: string;
            nationality: string;
            discord: {
                id: string;
                avatarUrl: string | null;
            };
            rsn: {
                main: string | null;
                alt: string | null;
            };
            membership: {
                active: boolean;
                /** Format: date-time */
                joinedAt: string | null;
                /** Format: date-time */
                leftAt: string | null;
                rank: components["schemas"]["RankSummary"];
                points: number;
            };
            diary: {
                points: number;
                masterDiaries: number;
                claimedTier: {
                    id: number;
                    name: string;
                } | null;
            };
            progression: {
                eligibleRank: components["schemas"]["RankSummary"] | null;
                nextRank: {
                    points: {
                        id: number;
                        name: string;
                        iconUrl: string | null;
                        requirements: {
                            clanPoints: number;
                            diaryPoints: number;
                            masterDiaries: number;
                        };
                    } | null;
                    diary: {
                        id: number;
                        name: string;
                        iconUrl: string | null;
                        requirements: {
                            clanPoints: number;
                            diaryPoints: number;
                            masterDiaries: number;
                        };
                    } | null;
                };
            };
            wom: {
                playerId: number;
                username: string;
                displayName: string;
                type: string;
                build: string;
                status: string | null;
                totalLevel: number | null;
                totalExp: number;
                totalEhp: number;
                totalEhb: number;
                timeToMax: number | null;
                timeTo200m: number | null;
                /** Format: date-time */
                updatedAt: string | null;
                /** Format: date-time */
                lastChangedAt: string | null;
                latestSnapshot?: components["schemas"]["Snapshot"];
            } | null;
        };
        Rank: {
            id: number;
            name: string;
            iconUrl: string | null;
            discordRoleId: string | null;
            requirements: {
                clanPoints: number;
                diaryPoints: number;
                masterDiaries: number;
                maintenancePoints: number;
            };
        };
        Submission: {
            id: number;
            item: {
                id: number | null;
                name: string | null;
            };
            valueMillions: number | null;
            /** @enum {string|null} */
            event: "bingo" | "leagues" | null;
            imageUrl: string | null;
            discordMessageUrl: string | null;
            /** Format: date-time */
            submittedAt: string;
            submittedBy: components["schemas"]["MemberRef"];
            participants: {
                id: string;
                displayName: string;
                points: number | null;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
